
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_airbnb'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_airbnb'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
vars:
  warehouse_by_env:
    feature: WH_TRANSFORM_DEV
    dev: WH_TRANSFORM_REC
    prod: WH_TRANSFORM_PROD
  tags_to_create: ["BUSINESS_OWNER", "SENSITIVITY_LEVEL"]
  table_tags: |
    int_tab_location:
      business_owner: "Equipe Data Marketplace"
      sensitivity_level: "low"
      columns:
        ID:
          business_owner: "Equipe Data Marketplace"
          sensitivity_level: "medium"
        CODE_VILLE:
          business_owner: "Equipe Data Marketplace"
          sensitivity_level: "low"

models:
  dbt_airbnb:
    staging:
      +materialized: view
      +schema: BRONZE
    intermediate:
      +materialized: view
      +schema: SILVER
    mart:
      +materialized: view
      +schema: GOLD
    +persist_docs:
      relation: true
      columns: true
    +pre-hook: 
      - >
        INSERT INTO MODEL_RUN_LOG
        (
          MODEL_NAME,
          DATABASE_NAME,
          SCHEMA_NAME,
          MATERIALIZATION,
          TARGET_NAME,
          START_TIME,
          STATUS,
          INVOCATION_ID
        )
        VALUES (
          '{{ this.name }}',
          '{{ this.database }}',
          '{{ this.schema }}',
          '{{ config.get("materialized") }}',
          '{{ target.name }}',
          CURRENT_TIMESTAMP(),
          'RUNNING',
          '{{ invocation_id }}'
        )
    +post-hook: 
      - >
        UPDATE MODEL_RUN_LOG
        SET
          END_TIME = CURRENT_TIMESTAMP(),
          DURATION_SEC = DATEDIFF(second, START_TIME, CURRENT_TIMESTAMP()),
          STATUS = 'SUCCESS'
        WHERE MODEL_NAME = '{{ this.name }}'
          AND INVOCATION_ID = '{{ invocation_id }}'

      - "{{ ensure_tags_and_apply(this) }}"