dbt_airbnb:
  outputs:
    feature:
      account: ttjpinf-jib75082
      database: AIRBNB_BI_DEV
      # Authentification sans mot de passe
      # Chemin vers la clé privée générée
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"
      role: DBT_DEV
      schema: BI
      threads: 4
      type: snowflake
      user: USER_DBT_DEV
      warehouse: WH_TRANSFORM_DEV
    dev:
      account: ttjpinf-jib75082
      database: AIRBNB_BI_REC
      # Authentification sans mot de passe
      # Chemin vers la clé privée générée
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"
      role: DBT_REC
      schema: BI
      threads: 4
      type: snowflake
      user: USER_DBT_REC
      warehouse: WH_TRANSFORM_REC
    prod:
      account: ttjpinf-jib75082
      database: AIRBNB_BI_PROD
      # Authentification sans mot de passe
      # Chemin vers la clé privée générée
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"
      role: DBT_PROD
      schema: BI
      threads: 4
      type: snowflake
      user: USER_DBT_PROD
      warehouse: WH_TRANSFORM_PROD
  target: feature
