dbt_airbnb:
  outputs:
    feature:
      account: ttjpinf-jib75082
      database: AIRBNB_BI_FEATURE
      private_key_path:  C:\Users\BenoitOTTAVI\Documents\snowflake_keys\rsa_key.pem
      role: accountadmin
      schema: BI
      threads: 4
      type: snowflake
      user: benoit
      warehouse: COMPUTE_WH
    dev:
      account: ttjpinf-jib75082
      database: AIRBNB_BI_DEV
      private_key_path:  C:\Users\BenoitOTTAVI\Documents\snowflake_keys\rsa_key.pem
      role: accountadmin
      schema: BI
      threads: 4
      type: snowflake
      user: benoit
      warehouse: COMPUTE_WH
    prod:
      account: ttjpinf-jib75082
      database: AIRBNB_BI
      private_key_path:  C:\Users\BenoitOTTAVI\Documents\snowflake_keys\rsa_key.pem
      role: accountadmin
      schema: BI
      threads: 4
      type: snowflake
      user: benoit
      warehouse: COMPUTE_WH
  target: feature
