dbt_airbnb:
  outputs:
    feature:
      account: ttjpinf-jib75082
      database: AIRBNB_BI_FEATURE
      # Authentification sans mot de passe
      # Chemin vers la clé privée générée
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"
      role: accountadmin
      schema: BI
      threads: 4
      type: snowflake
      user: benoit
      warehouse: COMPUTE_WH
    dev:
      account: ttjpinf-jib75082
      database: AIRBNB_BI_DEV
      # Authentification sans mot de passe
      # Chemin vers la clé privée générée
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"
      role: accountadmin
      schema: BI
      threads: 4
      type: snowflake
      user: benoit
      warehouse: COMPUTE_WH
    prod:
      account: ttjpinf-jib75082
      database: AIRBNB_BI
      # Authentification sans mot de passe
      # Chemin vers la clé privée générée
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH') }}"
      role: accountadmin
      schema: BI
      threads: 4
      type: snowflake
      user: benoit
      warehouse: COMPUTE_WH
  target: feature
